import os,  numpy as np, matplotlib.pyplot as plt

dir = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))

xa, ya = np.genfromtxt(dir+'/source/AST_Data_Normalised.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xa,ya) 
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.title('AST Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/AST_Normalised_Graph.png', dpi=300, bbox_inches='tight')

xb, yb = np.genfromtxt(dir+'/source/SA_Data_Normalised.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xb,yb) 
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.title('SA Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/SA_Normalised_Graph.png', dpi=300, bbox_inches='tight')



xl, yl = np.genfromtxt(dir+'/source/AST_Data.txt',delimiter='',unpack=True) 
xf, yf = np.genfromtxt(dir+'/source/AST_Data_Normalised.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xl, yl, label='AST Data')
plt.plot(xf, yf, label='AST Normalised Data')
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.legend(loc='best')
plt.title('AST Vs AST  Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/AST_Data_Vs_Normalised_Graph.png', dpi=300, bbox_inches='tight')

xm, ym = np.genfromtxt(dir+'/source/SA_Data.txt',delimiter='',unpack=True) 
xv, yv = np.genfromtxt(dir+'/source/SA_Data_Normalised.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xm, ym, label='SA Data')
plt.plot(xv, yv, label='SA Normalised Data')
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.legend(loc='best')
plt.title('SA Vs SA Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/SA_Data_Vs_Normalised_Graph.png', dpi=300, bbox_inches='tight')

xc, yc = np.genfromtxt(dir+'/source/AST_Data_Normalised.txt',delimiter='',unpack=True) 
xd, yd = np.genfromtxt(dir+'/source/SA_Data_Normalised.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xc, yc, label='AST Data')
plt.plot(xd, yd, label='SA Data')
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.legend(loc='best')
plt.title('AST Vs SA  Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/AST_Vs_SA_(Normalised)_Graph.png', dpi=300, bbox_inches='tight')

xe, ye = np.genfromtxt(dir+'/source/AST_Vs_SA.txt',delimiter='',unpack=True) 
plt.figure()
plt.plot(xe,ye) 
plt.xlabel('Pixel Value')
plt.ylabel('Pixel ADUs')
plt.title('AST/SA Normalised Spectrum Data Graph')
plt.savefig(dir+'/results/AST-SA_Graph.png', dpi=300, bbox_inches='tight')